---
  - src: ssh://git@github.com/netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.0.0"
    force: yes
    name: elastic
  - src: git@github.com:MaxNelipin/kibana-role.git
    scm: git
    version: "1.1.0"
    name: kibana
  - src: git@github.com:MaxNelipin/logstash-role.git
    scm: git
    version: "1.0.0"
    name: logstash
  - src: git@github.com:MaxNelipin/filebeat-role.git
    scm: git
    version: "1.2.1"
    name: filebeat


