---
  - name: Install elastic
    hosts: elasticsearch
    roles:
      - { role: elastic, elasticsearch_version: "{{ elk_stack_version }}" }
  - name: Install kibana
    hosts: kibana
    roles:
      - { role: kibana, kibana_version: "{{ elk_stack_version }}", el_instance_ip: "{{ hostvars['el-instance']['ansible_facts']['default_ipv4']['address'] }}" }
  - name: Install logstash
    hosts: elasticsearch
    roles:
      - { role: logstash, filebeat_version: "{{ elk_stack_version }}", el_instance_ip: "{{ hostvars['el-instance']['ansible_facts']['default_ipv4']['address'] }}", kb_instance_ip: "{{ hostvars['kb-instance']['ansible_facts']['default_ipv4']['address'] }}" }

  - name: Install filebeat
    hosts: filebeat
    roles:
      - { role: filebeat, filebeat_version: "{{ elk_stack_version }}", el_instance_ip: "{{ hostvars['el-instance']['ansible_facts']['default_ipv4']['address'] }}", kb_instance_ip: "{{ hostvars['kb-instance']['ansible_facts']['default_ipv4']['address'] }}" }
